[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
ecoquest_mobile = "4RoEXMwC3pvm1NYb8oXvcezJzsvxZmCwMgNUKZxCnju5"

[programs.localnet]
ecoquest_mobile = "4RoEXMwC3pvm1NYb8oXvcezJzsvxZmCwMgNUKZxCnju5"

[programs.mainnet]
ecoquest_mobile = "4RoEXMwC3pvm1NYb8oXvcezJzsvxZmCwMgNUKZxCnju5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
deploy-devnet = "anchor deploy --provider.cluster devnet"

[build]
shell = "/bin/bash"

